### ISSUE TITLE
Error in preprocessing_new.py: kiwisolver 

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DrugCell#27]
Command: train.sh

Steps:
```bash
git clone git@github.com:JDACS4C-IMPROVE/DrugCell.git
cd DrugCell/
conda create -n DrugCell python=3.9.15 anaconda
conda activate DrugCell
conda env update --name DrugCell --file environment.yml
pip install --upgrade pip
python3 -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 torchmetrics==0.11.1 --extra-index-url https://download.pytorch.org/whl/cu113
python3 -m pip install networkx
python3 -m pip install git+https://github.com/ECP-CANDLE/candle_lib@develop
sh ./train.sh 1 ./tmp
mkdir tmp
sh ./train.sh 1 ./tmp
```

Output:
```
./tmp//Data
Traceback (most recent call last):
  File "/home/wilke/tmp/DrugCell/preprocessing_new.py", line 13, in <module>
    import candle
  File "/homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/site-packages/candle/__init__.py", line 19, in <module>
    from .feature_selection_utils import (
  File "/homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/site-packages/candle/feature_selection_utils.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/site-packages/matplotlib/__init__.py", line 214, in <module>
    _check_versions()
  File "/homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/site-packages/matplotlib/__init__.py", line 208, in _check_versions
    module = importlib.import_module(modname)
  File "/homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/site-packages/kiwisolver/__init__.py", line 8, in <module>
    from ._cext import (
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /homes/wilke/miniconda3/envs/DrugCell/lib/python3.9/site-packages/kiwisolver/_cext.cpython-39-x86_64-linux-gnu.so)
```

**Comment by wilke** [comment]
Suggested solution `pip install kiwisolver=1.4.5`

**Comment by rohandavidg** [comment]
added this in the requirements
